name: CI/CD Pipeline 

on:
  push:
    - main


permissions:
  contents: read
  packages: write


jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set short git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: linerasteniaor
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/linerasteniaor/fastapi-app:latest
            ghcr.io/linerasteniaor/fastapi-app:${{ steps.vars.outputs.sha_short }}
